on:    
  workflow_dispatch:
  push:
  pull_request:

    branches:
      - main

jobs:
  job_info:
    runs-on: ubuntu-latest
    steps:
      - name: Message when push
        if: github.event_name == 'push'
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"           
      
      - name: Message when pull request
        if: github.event_name == 'pull_request'
        run: echo "Detta Ã¤r en pull request!"

      - name: Message when manual start
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manuell start!"

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]

    steps: 
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
